# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e52498b5cf1b67f9499e17edc6b5e84eeb7c77d754c3cacb48cdc0671697b146565c1a44ad047d115618f4d18970d0df43b81b62c04a3fae8748718dfc95bb64

test:
  secret_key_base: ab2fb22a637423e62d41ebef8bf8b3fb01152ea4f2c616ee8faed04a215ca929829bd17ba7b65ebbd0b91ff885036ac8c85572406a7645038c02b4ac265879de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
